backend:
  name: git-gateway
  branch: main

# Onde as fotos novas que o professor subir vão morar
media_folder: "assets/img"
# Como o site vai "chamar" essas fotos no código
public_folder: "assets/img"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "index.njk"
        label: "Página Inicial"
        name: "home"
        fields:
          - {label: "Título Principal", name: "title", widget: "string", required: false}
          - {label: "Subtítulo (Legenda)", name: "tagline", widget: "string", required: false}
          - {label: "Imagem de Fundo", name: "banner_image", widget: "image", required: false}
          - {label: "Imagem do Mascote", name: "mascot_image", widget: "image", required: false}
          - {label: "Nome do Professor", name: "teacher_name", widget: "string", required: false}
          - {label: "Escola", name: "school_name", widget: "string", required: false}
          - {label: "Disciplina", name: "subject_name", widget: "string", required: false}
          - {label: "Foto Professor", name: "card1_image", widget: "image", required: false}
          - {label: "Foto Sociologia", name: "card2_image", widget: "image", required: false}
          - {label: "Foto Temas", name: "card3_image", widget: "image", required: false}
          - {label: "Foto Projetos", name: "card4_image", widget: "image", required: false}S