backend:
  name: git-gateway
  branch: main # Mude para 'master' se seu branch principal for master

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "index.njk"
        label: "Página Inicial"
        name: "home"
        fields:
          - {label: "Título Principal", name: "title", widget: "string"}
          - {label: "Subtítulo", name: "tagline", widget: "string"}
          - {label: "Imagem de Fundo", name: "banner_image", widget: "image"}
          - {label: "Imagem do Mascote", name: "mascot_image", widget: "image"}
          - {label: "Nome do Professor", name: "teacher_name", widget: "string"}
          - {label: "Escola", name: "school_name", widget: "string"}
          - {label: "Disciplina", name: "subject_name", widget: "string"}
          - {label: "Foto Professor", name: "card1_image", widget: "image"}
          - {label: "Foto Sociologia", name: "card2_image", widget: "image"}
          - {label: "Foto Temas", name: "card3_image", widget: "image"}
          - {label: "Foto Projetos", name: "card4_image", widget: "image"}